// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXNqDijH8wXyn1ch9FWN2oaEiEPZ5bNA',
    appId: '1:702630409165:web:5b822aae769ac6c8128a84',
    messagingSenderId: '702630409165',
    projectId: 'mynotes-flutter-wattana',
    authDomain: 'mynotes-flutter-wattana.firebaseapp.com',
    storageBucket: 'mynotes-flutter-wattana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CsKIy9gXYiQtnY3zbKNU2eHXYw0Ot_U',
    appId: '1:702630409165:android:945ce23cd35247dc128a84',
    messagingSenderId: '702630409165',
    projectId: 'mynotes-flutter-wattana',
    storageBucket: 'mynotes-flutter-wattana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnaugZ0mZxwFPC5e7yHz6HyKuB3p-pVU',
    appId: '1:702630409165:ios:61d9845da64b818c128a84',
    messagingSenderId: '702630409165',
    projectId: 'mynotes-flutter-wattana',
    storageBucket: 'mynotes-flutter-wattana.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnaugZ0mZxwFPC5e7yHz6HyKuB3p-pVU',
    appId: '1:702630409165:ios:61d9845da64b818c128a84',
    messagingSenderId: '702630409165',
    projectId: 'mynotes-flutter-wattana',
    storageBucket: 'mynotes-flutter-wattana.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgXNqDijH8wXyn1ch9FWN2oaEiEPZ5bNA',
    appId: '1:702630409165:web:deaeca4b6bce0f64128a84',
    messagingSenderId: '702630409165',
    projectId: 'mynotes-flutter-wattana',
    authDomain: 'mynotes-flutter-wattana.firebaseapp.com',
    storageBucket: 'mynotes-flutter-wattana.firebasestorage.app',
  );

}